# These are supported funding model platforms

github: douglasjunior
patreon: douglasjunior # Replace with a single Patreon username
open_collective: rn-keyboard-manager # Replace with a single Open Collective username
custom: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=E32BUP77SVBA2
